-- AlterTable
ALTER TABLE `debt` ADD COLUMN `userId` VARCHAR(191) NOT NULL DEFAULT 'user_2RGtE7WfxIuDOPvjCbBON6PRb3V';

-- AlterTable
ALTER TABLE `loan` ADD COLUMN `userId` VARCHAR(191) NOT NULL DEFAULT 'user_2RGtE7WfxIuDOPvjCbBON6PRb3V';
